[gemspec] cleanup dependencies
rack, cuba, celluloid, ... are pulled from airplay gem
no need to lock their versions here

fixes:
$ gem install airplayer
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: airplayer requires reel (= 0.4.0), reel-rack (= 0.1.0), celluloid (= 0.15.2); airplay requires celluloid (>= 0.17.0), reel (~> 0.5.0), reel-rack (~> 0.2.2); celluloid-io requires celluloid (>= 0.15.0)